using System;
using System.Collections.Generic;
using System.Linq;
using Sungero.Core;
using Sungero.CoreEntities;
using lenspec.AutomatedSupportTickets.SubstitutionRequestTask;

namespace lenspec.AutomatedSupportTickets.Shared
{
  partial class SubstitutionRequestTaskFunctions
  {

    //Добавлено Avis Expert
    /// <summary>
    /// Заполнить имя документа.
    /// </summary>
    [Public]
    public void FillSubject()
    {
      _obj.Subject = lenspec.AutomatedSupportTickets.SubstitutionRequestTasks.Resources.AutogeneratedSubject;
      
      if (_obj.Prolongation == null || _obj.Substitute == null || _obj.SubstitutedUser == null)
        return;
      
      var name = string.Empty;      
      /* Тема в формате:
        Если Продление=Да, то Продление замещения для <Замещающий> за <Сотрудник>
        иначе Согласование замещения для <Замещающий> за <Сотрудник>
       */
      using (TenantInfo.Culture.SwitchTo())
      {
        if (_obj.Prolongation == true)
          name += lenspec.AutomatedSupportTickets.SubstitutionRequestTasks.Resources.ProlongationOfSubstitutionFormat(_obj.Substitute.Name,
                                                                                                                      _obj.SubstitutedUser.Name);
        else
          name += lenspec.AutomatedSupportTickets.SubstitutionRequestTasks.Resources.ApprovalOfSubstitutionFormat(_obj.Substitute.Name,
                                                                                                                  _obj.SubstitutedUser.Name);
      }
      if (!string.IsNullOrEmpty(name))
      {
        _obj.Subject = name;
      }
    }
    //конец Добавлено Avis Expert
  }
}