using System;
using System.Collections.Generic;
using System.Linq;
using Sungero.Core;
using Sungero.CoreEntities;
using lenspec.EtalonDatabooks.FlowFolderSetting;

namespace lenspec.EtalonDatabooks.Shared
{
  partial class FlowFolderSettingFunctions
  {

    //Добавлено Avis Expert
    /// <summary>
    /// Заполнить наименование записи справочника.
    /// </summary>       
    public void FillName()
    {
      // Имя в формате:
      // <Имя папки потока> для типа <Тип задачи>, <Тип задания> 
      var name = string.Empty;
      
      if (_obj.FolderName != null)
      {
        name = _obj.Info.Properties.FolderName.GetLocalizedValue(_obj.FolderName);
        if (_obj.TaskType != null)
        {
          name += " для типа " + _obj.TaskType.Name;
        }
      }
      else
      {
        name = lenspec.EtalonDatabooks.FlowFolderSettings.Resources.AutogeneratedName;
      }
      
      _obj.Name = name;
    }
    //конец Добавлено Avis Expert
  }
}